-- Rename, not drop-and-add: `error` becomes `firstError`, the write-once
-- forensic record of the FIRST failed attempt (`lastError` stays the
-- most-recent one and may be cleared when a replay settles `processed`).
--
-- Prisma's autogenerated diff for this change was `DROP COLUMN "error"` +
-- `ADD COLUMN "firstError"`, which silently discards whatever the column
-- holds. The column has no writer today, so both forms are equivalent here —
-- but the intent is a rename, and the SQL should say so rather than rely on
-- the column happening to be empty in every environment.
ALTER TABLE "StripeWebhookEvent" RENAME COLUMN "error" TO "firstError";
