#!/bin/sh
set -eu

umask 077
repo_root="$(git rev-parse --show-toplevel)"
state_dir="$repo_root/.worktree"
output="$state_dir/marketing-landing.env"
metadata="$state_dir/metadata.env"

if [ ! -f "$metadata" ] || [ ! -f "$repo_root/.env.worktree" ]; then
  printf 'Missing generated worktree configuration. Run `make init`.\n' >&2
  exit 1
fi

. "$metadata"
mkdir -p "$(dirname "$output")"
if [ -f "$output" ]; then
  if [ ! -f "$state_dir/generated-landing-env" ]; then
    printf 'Refusing to overwrite unowned %s.\n' "$output" >&2
    exit 1
  fi
  expected_checksum="$(sed -n '1p' "$state_dir/generated-landing-env")"
  actual_checksum="$(cksum "$output" | awk '{ print $1 ":" $2 }')"
  if [ "$expected_checksum" != "$actual_checksum" ]; then
    printf 'Refusing to overwrite modified %s. Remove it explicitly first.\n' "$output" >&2
    exit 1
  fi
fi
temp_file="$(mktemp "${output}.XXXXXX")"

"$repo_root/scripts/run-with-env.sh" sh -ec '
  test "${#MARKETING_DEMO_SERVICE_SECRET}" -ge 32
  cat <<EOF
# Generated by Prelude make landing-env. Server-only; do not commit.
HIRECALL_WORKTREE_ID=$HIRECALL_WORKTREE_ID
PORT=$LANDING_PORT
HOSTNAME=0.0.0.0
NEXT_PUBLIC_SITE_URL=$LANDING_URL
NEXT_PUBLIC_APP_URL=$CONSOLE_URL
PRELUDE_CANDIDATE_URL=$CANDIDATE_URL
MARKETING_DEMO_RETURN_TARGET=$MARKETING_DEMO_RETURN_TARGET
MARKETING_DEMO_SERVICE_SECRET=$MARKETING_DEMO_SERVICE_SECRET
EOF
' > "$temp_file"
chmod 600 "$temp_file"
mv "$temp_file" "$output"
cksum "$output" | awk '{ print $1 ":" $2 }' > "$state_dir/generated-landing-env"
chmod 600 "$state_dir/generated-landing-env"
printf 'Generated server-only landing environment at %s (mode 0600).\n' "$output"
